### PR TITLE
Update deps and use AndroidX

### PR DESCRIPTION
**Pull request by SUPERCILEX**
This change updates Gradle, the AGP, and library dependencies. **Importantly, this PR makes the library AndroidX compatible.**

_Note about the Gradle update:_ I didn't upgrade to 6.1 because [this code](https://github.com/auth0/oss-library-gradle-plugin/blob/d5aad086cfc2b598c56c325f1582eeece1f30d4a/src/main/groovy/com/auth0/gradle/oss/AndroidLibraryPlugin.groovy#L293-L304) is incompatible with Gradle 6.x.

### CODE REVIEW

**Comment by lbalmaceda** [comment]
Thanks! I knew running `jetifier` makes a project (and its dependencies, like this library) be ready for AndroidX anyway, even if that increases the compilation time. 

Did you run the migration tool to generate this?

**Comment by SUPERCILEX** [comment]
Right, the jetifier will deal with it but makes things slower so it would be nice to start killing it.

And no, I did all this by hand since you were just using the annotations.

**Comment by lbalmaceda** [comment]
I have to ask. What about those still using the old support libraries in their app? Would they find this as breaking change if they have jetifier turned off?

**Comment by SUPERCILEX** [comment]
Correct, this is a breaking change for people still on the support library (so the new version of this lib should be 2.0.0). However, given that it's been 2 years since the announcement, it is expected for libraries to depend on AndroidX. All major libraries are now on AndroidX: Play Services, Firebase, Glide, Leak Canary, Easy Permissions, etc.

**Comment by SUPERCILEX** [comment]
@lbalmaceda any updates?

**Comment by lbalmaceda** [comment]
Yes, we will plan a major release, hopefully for this Q.

**Comment by SUPERCILEX** [comment]
@lbalmaceda Do you have a timeline? I'd like to also do https://github.com/auth0/Auth0.Android, but I want to make sure the changes will go through.

**Comment by lbalmaceda** [comment]
Not a specific one. We take our time to plan majors releases so we remove deprecated stuff, bump dependencies to latest majors (i.e. okhttp), etc. I can tell you it's slowly moving towards that. I just pushed an update to our oss-release plugin supporting the latest gradle version.

**Comment by SUPERCILEX** [comment]
@lbalmaceda Gotya, please let me know what I can do to help. Regarding okhttp, I don't think you'll be able to upgrade since they now require API 21+.

Would you like me to bump Gradle to 6.1.1? And should I submit an AndroidX migration PR for the core Auth0 lib? Also, any reason this PR can't be merged and just not released?

**Comment by lbalmaceda** [comment]
Let me create a new branch for the next major and ask for some standard protection settings to be applied first. The same would be applied to any other SDK requiring a new major release.

**Comment by lbalmaceda** [comment]
@SUPERCILEX I just created branch `2.0.0-DEV`. Please, use that as "base branch" for PRs that belong to the next major such as this one. If you run into many conflicts, you might want to close this and re-open a different one.

> Regarding okhttp, I don't think you'll be able to upgrade since they now require API 21+.

I think `Auth0.Android` is using OKHttp 2 still, moving to v3 (not v4) should be feasible. 

> Would you like me to bump Gradle to 6.1.1?

Yes, please. Note that you can bump the android OSS plugin to the latest version `0.11.0` that supports gradle 6x

> And should I submit an AndroidX migration PR for the core Auth0 lib? 

Yes, I'll do the same and create a similar branch for you to open that PR against it. Mind bumping the OSS plugin as well as gradle versions.

**Comment by SUPERCILEX** [comment]
Done. I'll create the PR for `Auth0.Android` tomorrow. :+1:

**Pull request merged**
