### PR TITLE
remove unused `libs` dependency

### PR DESCRIPTION
**Pull request by lukaszkalnik**
Just removed the `libs` dependency (not used anyway) from `build.gradle`.

### CODE REVIEW

**Comment by lbalmaceda** [comment]
Hey @lukaszkalnik thanks. Yes, those are not used but the problem is that the android plugin re-adds that line every time we move to a newer version of the plugin, so I rather keep it. It doesn't hurt anyway :)

**Comment by lukaszkalnik** [comment]
Hey @lbalmaceda ! How is it possible that the Android plugin modifies your build.gradle? Aren't you simply updating the plugin version manually? 

We've actually run into problems when distributing a library through Artifactory because of the line which I removed here, I think POM was not generated correctly.
But if you say it doesn't hurt in your case then it's fine.

**Comment by lbalmaceda** [comment]
I remember working on a project on the last week where this line wasn't present but after bumping some android plugin or maybe re-importing the project, this line reappeared. My point is this can happen to anyone collaborating with this project and if you remove it now it will reappear soon or later. It was there from the beginning and this project doesn't have a `libs` folder with jar files in it, so this has no effect on the project building stage. 
That also means that when we prepare the package to upload to bintray and central, no additional dependencies are included because of that line. Rest assure this is not the issue you're mentioning, at least for this library. 
Cheers

**Comment by lukaszkalnik** [comment]
Understand. Thank you for the thorough explanation 👍

**Pull request closed without merging**
