### PR TITLE
Feature: get sub claims from claim object.

### PR DESCRIPTION
**Pull request by LiYing2010**
Feature: get sub claims from claim object.

Issue: https://github.com/auth0/JWTDecode.Android/issues/21

### CODE REVIEW

**Comment by LiYing2010** [comment]
Mr @lbalmaceda   and Mr @hzalaz  : 
Could you please review and merge this when you get time?
Thanks very much

**Comment by cloudjubei** [comment]
Would be great if someone would finally merge this in - seriously needed feature.
@lbalmaceda and @hzalaz please look into this

**Comment by Crysis21** [comment]
We need this!

**Comment by PabloHazan** [comment]
Please merge it, we really need it

**Comment by lbalmaceda** [comment]
Closing in favor of #41.

**Pull request closed without merging**
